<?php
$donnees = array(
    'Accompagnements'=>array(
        'la_sauce_piquante_jamaicaine'=>array(
            'titre'=>'La sauce piquante Jamaïcaine',
            'intro'=>'Les amateurs de sauce piquante seront choyés avec cette recette. Comparé à ça, la sauce tabasco, c\'est du biberon.',
            'description'=>'Tout d\'abord, je tiens à lever mon chapeau à un fabricant de sauce piquante du Kensas, Original Juan Specialty Foods, pour l\'image de sa marque "Pain is good".',
            'legende'=>'Pain is good',
            'ingredients'=>array(
                array('quantite'=>'200', 'unite'=>'g', 'ingredient'=>'piments habanero jaunes ou orangés, frais, équeutés et émincés avec les pépins (environ une vingtaine)', ),
                array('quantite'=>'1/2', 'unite'=>'tasse', 'ingredient'=>'chair de mangue en petits dés', ),
                array('quantite'=>'1/2', 'unite'=>'tasse', 'ingredient'=>'chair de papaye en petits dés', ),
                array('quantite'=>'1/2', 'unite'=>'tasse', 'ingredient'=>'chair de tomates rouges en petits dés', ),
                array('quantite'=>'1/2', 'unite'=>'tasse', 'ingredient'=>'cassonade foncée', ),
                array('quantite'=>'1 1/2', 'unite'=>'tasse', 'ingredient'=>'vinaigre de vin rouge (6 % d\'acide acétique, minimum)', ),
                array('quantite'=>'', 'unite'=>'', 'ingredient'=>'jus de 2 citrons verts', ),
                array('quantite'=>'', 'unite'=>'', 'ingredient'=>'zestes fins d\'un citron vert', ),
                array('quantite'=>'3', 'unite'=>'', 'ingredient'=>'échalotes grises émincées', ),
                array('quantite'=>'3', 'unite'=>'', 'ingredient'=>'gousses d\'ail pelées, écrasées et hachées menu', ),
            ),
            'instructions'=>array(
                'Placez tout ça dans une petite casserole en inox ou en verre et porter à frémissements en remuant toujours.',
                'Laisser mijoter tout doucement en remuant souvent pour 20 ou 25 minutes.',
                'Retirer du feu, couvrir et laisser tiédir.',
                'Passez le tout au mélangeur pour obtenir une consistance lisse. Attention aux éclaboussures. Goûtez, avec un verre de lait sous la main.',
                'Verser le tout dans la casserole et reporter à ébullition, à feu moyen, en remuant toujours. Si c\'est trop épais, ajoutez du vinaigre ou du jus de citron dilué dans autant d\'eau. Laisser bouillir une minute avant d\'empoter.',
                'Empoter en laissant <span class="fraction"><sup>1</sup>/<sub>4</sub></span> de pouce (6 mm) d\'espace d\'air irrespirable sous le goulot.',
            ),
        ),
		'sauce_a_big_mac'=>array(
			'titre'=>'Sauce à Big Mac',
			'intro'=>'Tout le monde s\'endent pour dire qu\'ils sont; EXCELLENTS, DÉBILLES Ais-je besoin de vous dire combien j\'ai fait des p\'tits Heureux hier soir avec ces Big Mac maison!!',
			'description'=>'<p>Non sans blague le goût est identique!!</p><p>Pour les boulettes, j\'ai tout simplement pris de la viande hachée très très maigre dont j\'ai mélangé un sachet de soupe à l\'oignon ainsi que d\'un peu de thym et du poivre. J\'ai cuit et fait les hamburgers comme au Mc Do!! Bon ils ne sont pas aussi beaux mais ils goûtent pareille par exemple</p>',
			'legende'=>'La vraie recette de sauce à Big Mac',
			'ingredients'=>array(
				array('quantite'=>'1/4', 'unite'=>'tasse', 'ingredient'=>'mayonnaise', ),
				array('quantite'=>'4', 'unite'=>'c à thé', 'ingredient'=>'relish sucrée (pas mettre le jus)', ),
				array('quantite'=>'1', 'unite'=>'c à table', 'ingredient'=>'oignon haché', ),
				array('quantite'=>'1', 'unite'=>'c à thé', 'ingredient'=>'vinaigre blanc', ),
				array('quantite'=>'1', 'unite'=>'c à thé', 'ingredient'=>'sucre', ),
				array('quantite'=>'<span class="fraction"><sup>1</sup>/<sub>8</sub></span>', 'unite'=>'c à thé', 'ingredient'=>'sel', ),
				array('quantite'=>'2', 'unite'=>'c à table', 'ingredient'=>'vinaigrette française (orange)', ),
			),
            'instructions'=>array(
				'Bien mélanger toutes les ingrédients ensemble.',
				'Laisser reposer quelques heures, au réfrigérateur',
			),
		),
    ),
	'Déjeuners'=>array(
		'porridge'=>array(
			'titre'=>'Porridge à la pomme et à la cannelle',
			'intro'=>'La combinaison de la texture de la pomme froide sucrée et acidulée et du crémeux porridge est un plaisir pour le palais. Parfait petit déjeuner réconfortant pour un matin froid.',
			'legende'=>'Porridge à la pomme et à la cannelle',
			'description'=>'<p>Les flocons d\'avoine utilisés pour réaliser le porridge sont reconnus comme un des aliments les plus nutritifs, aussi les plus simples à cuisiner et les plus abordables.</p><p>Chaque foyer en Irlande a sa propre méthode de préparation du porridge, mais la mienne semble varier en fonction de mon humeur.</p><p>Les matins où je suis pressé, je le prépare au four à micro-ondes avec un peu de miel et d\'eau, mais les jours où j\'ai le temps, voici comment je le cuisine...</p>',
			'ingredients'=>array(
				array('quantite'=>'250', 'unite'=>'g', 'ingredient'=>'flocons d\'avoine'),
				array('quantite'=>'480', 'unite'=>'ml', 'ingredient'=>'lait de chèvre ou d\'eau'),
				array('quantite'=>'1', 'unite'=>'', 'ingredient'=>'grosse pomme râpée'),
				array('quantite'=>'', 'unite'=>'', 'ingredient'=>'Un peu de cannelle en poudre'),
				array('quantite'=>'', 'unite'=>'', 'ingredient'=>'Un filet de miel pour donner du goût'),
			),
			'instructions'=>array(
				'Râper la pomme juste avant de servir pour éviter qu\'elle brunisse.',
				'Mélanger dans une petite casserole le lait avec les flocons d\'avoine et faire cuire à feu moyen en remuant constamment. Il faut en général 10 minutes pour obtenir la bonne consistence.',
				'Ajouter la pomme râpée et mélanger.',
				'Saupoudrer de cannelle, verser un filet de miel et servir directement.',
				'Un déjeuner complet pour bien démarrer la journée!',
			),
		),
    ),
	'Desserts'=>array(
		'le_sucre_a_la_creme'=>array(
			'titre'=>'Le sucre à la crème',
			'intro'=>'Je pourrais en faire toute l\'année... Mais non !.. Je n\'en fais que pour Noël... C\'est la sucrerie la meilleure que je connaisse... c\'est... n\'ayons pas peur des mots... jouissif pour le palais... et c\'est la gourmandise, qui pour moi, représente le mieux Noël... et le Québec !',
			'description'=>'<p>Il faut que le sucre à la crème se tienne mais qu il soit fondant dans la bouche.</p><p>Si vous l\'avez trop cuit, il sera cassant et grumeleux..et c\'est carrément moins bon !</p><p>Il existe beaucoup de variantes et de recettes, mais pour mes proches et moi même, cette recette est la meilleure.</p><h2>Note importante</h2><p>Avant de commencer, je vous conseille vivement de tarer votre thermomètre à bonbons.</p><p>Faire bouillir de l\'eau et y plonger le thermomètre. Si il est bien "réglé" il devrait être à 100 C....si ce n\'est pas le cas, ajouter ou diminuer en fonction de température demandée pour obtenir un sucre à la crème parfait.</p>',
			'legende'=>'Le meilleur des sucres à la crème',
			'ingredients'=>array(
				array('quantite'=>'2', 'unite'=>'tasses', 'ingredient'=>'creme 35%'),
				array('quantite'=>'2 1/4', 'unite'=>'tasses', 'ingredient'=>'cassonade'),
				array('quantite'=>'2', 'unite'=>'c à soupe', 'ingredient'=>'sucre'),
				array('quantite'=>'2', 'unite'=>'c à soupe', 'ingredient'=>'sirop de maïs ( peut être remplacé par du sirop de canne à sucre ou du sirop d\'érable )'),
			),
			'instructions'=>array(
				'Dans une casserole, mélanger tous les ingrédients.',
				'Porter à ébullition et cuire a feu vif environ 20 mn, ou jusqu\'à ce qu\'un thermomètre à bonbons indique 116 C (241 F ).',
				'Retirer du feu et laissez tiédir 10 mn.',
				'Fouetter à vitesse élevée pendant 5 mn avec le batteur électrique. (je jauge à l\'oeil..ça épaissit )',
				'Étendre dans le moule carré, chemisé, de 8" ( 20 cm ).',
				'Couvrir et laisser refroidir plusieurs heures.',
				'Découper en carres et servir.',
			),
		),
		'brownies_au_tabasco'=>array(
			'titre'=>'Brownies au tabasco',
			'intro'=>'Ca faisait un bon ptit moment que ça me démangeait... Maintenant c\'est fait, j\'ai réalisé mon premier gâteau au tabasco!',
			'description'=>'<p>Et oui, j\'ai récidivé, c\'est plus fort que moi... Pourtant après le fameux gâteau choco-mayo (très bon, il faut quand même le dire) j\'avais promis que je ne recommencerai plus. Non, fini les gâteaux louches avec des ingrédients incongrus! J\'ai quand même tenu presqu\'un mois, c\'est pas mal, non?</p><p>Et en plus cette recette vaut vraiment le détour, ces brownies sont tout simplement "perfect": "fudgy" à l\'intérieur et "crunchy" sur le dessus, et tellement hhhhhuuuuuummmm!!!!!! Ah, si, juste un petit bémol: si le tabasco sublime la saveur du chocolat au moment où on les mange, il reste un petit arrière goût pimenté, que je ne trouve pas désagréable (le tabasco et moi ne faisons qu\'un!) mais qui pourrait peut-être gêner certaines personnes. C\'est pourquoi je pense qu\'il faudrait peut-être diminuer la quantité de tabasco.</p><p>Et puis même si vous voulez pas mettre de tabasco dedans, essayez quand même cette recette sans tabasco, rien que pour la texture vraiment à tomber...</p><p>Bon, sinon j\'ai trouvé la recette de ces Sweet and spicy brownies (en fait plus "spicy" que "sweet"... j\'ai suivi la recette à la lettre pour la quantité de tabasco et je crois que pour les palais sensibles, dont je ne fais pas partie, 1 cs c\'est un peu trop!) sur le site de la marque Tabasco. Comme c\'est en anglais je vous fais la traduction en direct live et avec les conversions en bonus!</p>',
			'legende'=>'Brownies au tabasco',
			'ingredients'=>array(
				array('quantite'=>'115', 'unite'=>'g', 'ingredient'=>'chocolat noir dessert corsé'),
				array('quantite'=>'3/4', 'unite'=>'tasse', 'ingredient'=>'beurre ou margarine (ce qui fait en gros 125 g)'),
				array('quantite'=>'2', 'unite'=>'tasses', 'ingredient'=>'sucre en poudre ( j\'en ai mis qu\'1 et 1/2 soit 300 g)'),
				array('quantite'=>'3', 'unite'=>'', 'ingredient'=>'gros oeufs'),
				array('quantite'=>'1', 'unite'=>'tasse', 'ingredient'=>'farine'),
				array('quantite'=>'5 à 15', 'unite'=>'gouttes', 'ingredient'=>'tabasco selon les goûts (dans la recette originale ils en mettent 1 cs, mais c\'est vrraiment trop!)'),
				array('quantite'=>'1/2', 'unite'=>'tasse', 'ingredient'=>'pépites de chocolat'),
				array('quantite'=>'1/2', 'unite'=>'tasses', 'ingredient'=>'cerneaux de noix concassés'),
			),
			'instructions'=>array(
				'Mélanger le chocolat et la margarine (ou beurre) dans un saladier puis faire fondre au micro-ondes ou au bain-marie en remuant régulièrement. Ajouter le sucre et laisser un peu refroidir.',
				'Préchauffer le four à 180°C (th.6) et beurrer ou tapisser de papier sulfurisé un moule carré de 22x22 cm (ou sortir son moule silicone...).',
				'Ajouter les oeufs, 1 à 1, au mélange chocolaté en remuant bien après chaque oeuf.',
				'Ajouter ensuite la farine et le tabasco et bien mélanger.',
				'Ajouter les noix et les pépites de chocolat.',
				'Verser dans le moule et enfourner pour 35 à 40 minutes ou jusqu\'à ce qu\'une lame de couteau ressorte propre (pour moi 25-30 min).',
				'Laisser refroidir complétement dans le moule sur une grille.',
				'Voilà, yapuka couper en carrés et servir (sans dire à vos "cobayes" ce que vous avez mis dedans, ils s\'en rendront compte bien assez tôt...).',
			),
		),
		'tarte_a_la_farlouche'=>array(
			'titre'=>'Tarte à la farlouche',
			'intro'=>'La tarte à la farlouche est un dessert Québécois qu’on ne peut pas réinventer. C’est en fait une tarte à la mélasse. La farlouche (ou forlouche) est finalement le nom de la sauce à la mélasse composée de raisins secs.',
			'description'=>'Je préfère d’habitude manger la mélasse avec les crêpes du matin, mais j’avoue que j’ai tout de même été séduie par cette recette traditionnelle.',
			'legende'=>'Tarte à la farlouche',
			'ingredients'=>array(
				array('quantite'=>'1', 'unite'=>'tasse', 'ingredient'=>'mélasse'),
				array('quantite'=>'1', 'unite'=>'tasse', 'ingredient'=>'cassonade'),
				array('quantite'=>'3', 'unite'=>'', 'ingredient'=>'oeufs battus'),
				array('quantite'=>'1', 'unite'=>'c. à table', 'ingredient'=>'beurre'),
				array('quantite'=>'1', 'unite'=>'tyasse', 'ingredient'=>'lait'),
				array('quantite'=>'2', 'unite'=>'c. à table', 'ingredient'=>'fécule de maïs'),
				array('quantite'=>'1', 'unite'=>'tasse', 'ingredient'=>'raisins'),
				array('quantite'=>'1', 'unite'=>'', 'ingredient'=>'pâte brisée'),
			),
			'instructions'=>array(
				'Dans une casserole, faites chauffer à feu moyen la mélasse, la cassonade, les oeufs, le beurre et le lait.',
				'Ajoutez la fécule de maïs et laissez cuire un peu en remuant constamment (pour que ça épaississe). Ajoutez les raisins hors du feu et mélangez.',
				'Versez la préparation dans le fond de la tarte et enfournez environ 35 minutes à 350 degrés F.',
				'Laissez refroidir complètement avant de couper.',
			),
		),
	),
	'Boissons'=>array(
		'hypocras'=>array(
			'titre'=>'Hypocras',
			'intro'=>'Si l’hypocras fut l’apéritif médiéval par excellence, la recette est bien plus ancienne. C’est au Ve siècle avant J.C. que le célèbre médecin grec Hippocrate inventa la précieuse recette qualifiée de « potion magique ».',
			'description'=>'<p>Il y a de nombreuses recettes de cette fameuse boisson tonifiante et même aphrodisiaque (disait-on). C’est en fait un vin rouge ou blanc auquel on ajoute du sucre pour ensuite faire macérer, certains font cuire, de nombreuses plantes et épices.</p><p>Le roi Henri IV, Louis XIV et Rabelais furent parmi ses plus célèbres adeptes. Voici la traduction de la recette du 15e siècle tirée du « Viandier » de Taillevent :</p>',
			'legende'=>'Les épices pour faire de l\'hypocras',
			'ingredients'=>array(
				array('quantite'=>'10', 'unite'=>'', 'ingredient'=>'clous de girofle'),
				array('quantite'=>'10', 'unite'=>'', 'ingredient'=>'gousses de cardamome'),
				array('quantite'=>'30', 'unite'=>'g', 'ingredient'=>'cannelle'),
				array('quantite'=>'60', 'unite'=>'g', 'ingredient'=>'gingembre râpé'),
				array('quantite'=>'1', 'unite'=>'', 'ingredient'=>'bouteille de vin rouge (du bourgogne)'),
				array('quantite'=>'100', 'unite'=>'g', 'ingredient'=>'sucre environ.'),
			),
			'instructions'=>array(
				'Broyez le girofle, la cardamome et la cannelle;',
				'Mélangez le gingembre râpé.',
				'Disposez le tout dans une fine toile que vous nouez fortement.',
				'Versez le vin dans un récipient avec les épices dans le sac de toile.',
				'Ajoutez le sucre;',
				'Couvrez et laissez macérer au moins 3 Heures.',
				'Avec une macération plus longue (attention à ne pas éventer le vin toutefois...), les arômes seront bien sûr plus prononcés.',
				'Une fois la macération terminée, retirer le sac d\'épices, filtrez le vin jusqu\'à ce qu\'il n\'y ait plus de dépôts...',
			),
		),
		'claret'=>array(
			'titre'=>'Claret',
			'intro'=>'Le Claret est l’équivalent de l’Hypocras mais à base de vin blanc au lieu du vin rouge.',
			'description'=>'Ce vin épicé devient petit à petit au cours du XIIIe siècle une boisson servie lors de banquet. Il sert en vin de dessert, le gingembre aidant à la digestion. ',
			'legende'=>'',
			'ingredients'=>array(
				array('quantite'=>'100', 'unite'=>'cl', 'ingredient'=>'vin blanc sec'),
				array('quantite'=>'8', 'unite'=>'g', 'ingredient'=>'cannelle en bâton'),
				array('quantite'=>'20', 'unite'=>'g', 'ingredient'=>'gingembre frais (ou 8 g de gingembre en poudre)'),
				array('quantite'=>'1', 'unite'=>'', 'ingredient'=>'feuille de laurier'),
				array('quantite'=>'1/2', 'unite'=>'', 'ingredient'=>'racine de galanga'),
				array('quantite'=>'2', 'unite'=>'', 'ingredient'=>'clous de girofle'),
				array('quantite'=>'1/2', 'unite'=>'', 'ingredient'=>'grappe de poivre long'),
				array('quantite'=>'250', 'unite'=>'g', 'ingredient'=>'de miel'),
			),
			'instructions'=>array(
				'Faites bouillir le miel, écumez-le et versez-le dans un saladier contenant le vin.',
				'Ajoutez les épices : les bâtons de cannelle éclatés, le gingembre épluché et tranché, le laurier, la racine de galanga écrasée (au marteau par exemple) ou râpée, le clou de girofle et le poivre long écrasé dans un mortier.',
				'Laissez reposer quatre heures (moins si les épices sont toutes en poudre).',
				'Mettez en bouteille après avoir retiré les épices, par exemple en passant le liquide à travers une passoire. Mettez au frais 24 heures, puis filtrez dans un filtre à café.',
				'Le claret est meilleurs s\'il attend une semaine au frais. Conservez-le toujours au frais, pour éviter qu\'une fermentation ne redémarre.',
				'Remarques :',
				'Je ne mets pas de nard indien, car je n\'en ai pas encore trouvé. Si vous en avez, rajoutez-le.',
				'L\'once valait environ 30 g, le sextarius 570 ml et le quartarius, le quart du sextarius : je ne respecte pas les quantités données dans la recette originale, car le résultat est insupportable pour nos palais modernes. ',
			),
		),
	),
);
